"""
Project: 3D Printing Model Prompt
File: /home/user/3d-printing-model-prompt/src/threedprompt/thickness.py
Description: Increases the wall thickness of a model. Two strategies,
    tried in order:
      1. Regenerate from source - if the model was generated by this
         service via OpenSCAD and its .scad source declares a
         `wall_thickness` variable, bump that variable and re-render.
         Cleanest result (still fully parametric), zero LLM cost.
      2. Mesh shell - for any other file (a Blender-sourced model, or an
         arbitrary STL/OBJ a user uploads with no known source), load the
         mesh into headless Blender and apply a Solidify modifier. Works
         on any mesh regardless of how it was made; no LLM call needed
         either, since this is a fixed deterministic script.
Inputs: A model file path (STL/OBJ), a thickness increase in mm, and
    optionally the sidecar spec describing how the model was generated
    (see storage.py).
Outputs: Path to the new, thickened STL file.
Troubleshooting:
    - "no wall_thickness variable found in source": the .scad file wasn't
      generated with a recognized thickness variable (e.g. a hand-edited
      file) - falls back to mesh-shell automatically, no action needed.
    - Mesh-shell results can self-intersect on very thin or non-manifold
      input meshes; Solidify's "even thickness" + "high quality normals"
      options are enabled by default to reduce this, but a badly
      non-manifold upload may still need repair first (e.g. Blender's
      3D Print Toolbox / "Make Manifold") before shelling.
"""

from __future__ import annotations

import re
import shutil
import subprocess
from pathlib import Path

from threedprompt.config import settings
from threedprompt.logging_config import get_logger
from threedprompt.openscad_generator import WALL_THICKNESS_VAR, OpenScadGenerationError, render_scad_to_stl

logger = get_logger(__name__)


class ThicknessError(RuntimeError):
    """Raised when neither the regenerate-from-source nor mesh-shell strategy can succeed."""


_WALL_VAR_RE = re.compile(rf"^({WALL_THICKNESS_VAR}\s*=\s*)([\d.]+)(\s*;.*)$", re.MULTILINE)


def _read_wall_thickness(scad_source: str) -> float | None:
    """Return the current wall_thickness value declared in a .scad source, or None if absent."""
    match = _WALL_VAR_RE.search(scad_source)
    return float(match.group(2)) if match else None


def _bump_wall_thickness(scad_source: str, amount_mm: float) -> tuple[str, float]:
    """Increase the declared wall_thickness by amount_mm, returning the new source and new value."""
    match = _WALL_VAR_RE.search(scad_source)
    if not match:
        raise ThicknessError(f"no {WALL_THICKNESS_VAR} variable found in source")
    new_value = float(match.group(2)) + amount_mm
    new_source = _WALL_VAR_RE.sub(rf"\g<1>{new_value}\g<3>", scad_source, count=1)
    return new_source, new_value


def regenerate_from_source(scad_path: Path, amount_mm: float, output_stl_path: Path) -> float:
    """
    Bump the wall_thickness variable in an OpenSCAD source file and re-render.

    Returns the new wall thickness value in mm. Raises ThicknessError if
    the source has no recognizable wall_thickness variable.
    """
    scad_source = scad_path.read_text()
    new_source, new_value = _bump_wall_thickness(scad_source, amount_mm)
    scad_path.write_text(new_source)
    try:
        render_scad_to_stl(scad_path, output_stl_path)
    except OpenScadGenerationError as exc:
        raise ThicknessError(f"re-render after thickness bump failed: {exc}") from exc
    logger.info("Regenerated %s with wall_thickness=%.3fmm from source.", output_stl_path, new_value)
    return new_value


# __BLENDER_SCRIPTS_DIR__ is replaced (str.replace, not .format -- this
# template already uses literal {{ }} braces in f-strings below, and
# nesting a second format/f-string layer around that gets unreadable fast)
# with blender_scripts/'s real absolute path by mesh_shell() below, so this
# generated script can `import _shared` and reuse its import_mesh() (now
# also handling .3dm) / export_mesh() / quad_remesh() instead of
# duplicating that logic a second time here.
_SOLIDIFY_SCRIPT_TEMPLATE = """\
import bpy
import sys

sys.path.insert(0, "__BLENDER_SCRIPTS_DIR__")
import _shared

if __name__ == "__main__":
    argv = sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else []
    input_path, output_path, thickness_mm = argv[0], argv[1], float(argv[2])
    quad_target_faces = int(argv[3]) if len(argv) > 3 else 0

    bpy.ops.object.select_all(action="SELECT")
    bpy.ops.object.delete(use_global=False)

    _shared.import_mesh(bpy, input_path)
    mesh_objects = [obj for obj in bpy.context.scene.objects if obj.type == "MESH"]
    if not mesh_objects:
        raise RuntimeError(f"no mesh objects found after importing {{input_path}}")

    for obj in mesh_objects:
        bpy.context.view_layer.objects.active = obj
        modifier = obj.modifiers.new(name="Solidify", type="SOLIDIFY")
        modifier.thickness = thickness_mm
        modifier.offset = 0.0
        modifier.use_even_offset = True
        modifier.use_quality_normals = True
        bpy.ops.object.modifier_apply(modifier=modifier.name)

    if quad_target_faces > 0:
        merged = bpy.context.view_layer.objects.active
        if len(mesh_objects) > 1:
            bpy.ops.object.select_all(action="DESELECT")
            for obj in mesh_objects:
                obj.select_set(True)
            bpy.ops.object.join()
            merged = bpy.context.view_layer.objects.active
        _shared.quad_remesh(bpy, merged, quad_target_faces)

    bpy.ops.object.select_all(action="SELECT")
    _shared.export_mesh(bpy, output_path)
"""


def _blender_binary_path() -> str:
    """Resolve the configured blender binary, raising a clear error if it isn't on PATH."""
    resolved = shutil.which(settings.blender_binary) or (
        settings.blender_binary if Path(settings.blender_binary).is_file() else None
    )
    if not resolved:
        raise ThicknessError(
            f"blender binary '{settings.blender_binary}' not found on PATH. "
            "Install Blender or set BLENDER_BINARY to its full path."
        )
    return resolved


_BLENDER_SCRIPTS_DIR = Path(__file__).resolve().parent / "blender_scripts"


def mesh_shell(input_path: Path, amount_mm: float, output_dir: Path, *, quad_target_faces: int = 0) -> Path:
    """
    Increase wall thickness of an arbitrary mesh file by applying a
    Blender Solidify modifier of amount_mm and re-exporting.

    quad_target_faces (default 0 = disabled): when > 0, retopologizes the
    result into roughly this many quad-dominant faces via QuadriFlow after
    thickening. Mainly topology/cosmetic -- every STL export re-triangulates
    regardless -- but see _shared.quad_remesh's docstring for why a target
    at or below the mesh's natural face count isn't guaranteed watertight
    even with the repair pass that runs right after it.

    Works regardless of how the mesh was originally produced. Raises
    ThicknessError on missing binary, unsupported format, or a Blender
    failure (with its traceback tail included).
    """
    if amount_mm > settings.max_wall_thickness_mm:
        raise ThicknessError(
            f"requested thickness increase {amount_mm}mm exceeds MAX_WALL_THICKNESS_MM={settings.max_wall_thickness_mm}"
        )
    output_dir.mkdir(parents=True, exist_ok=True)
    script_path = output_dir / "solidify.py"
    output_stl_path = output_dir / "model.stl"
    script_path.write_text(_SOLIDIFY_SCRIPT_TEMPLATE.replace("__BLENDER_SCRIPTS_DIR__", str(_BLENDER_SCRIPTS_DIR)))

    binary = _blender_binary_path()
    result = subprocess.run(
        [
            binary,
            "--background",
            "--python",
            str(script_path),
            "--",
            str(input_path),
            str(output_stl_path),
            str(amount_mm),
            str(quad_target_faces),
        ],
        capture_output=True,
        text=True,
        timeout=settings.cad_subprocess_timeout_seconds,
    )
    if result.returncode != 0 or not output_stl_path.exists():
        tail = "\n".join(result.stdout.splitlines()[-40:] + result.stderr.splitlines()[-40:])
        raise ThicknessError(f"blender solidify shell failed (exit {result.returncode}): {tail}")
    logger.info("Shelled %s by %.3fmm via Blender Solidify -> %s.", input_path, amount_mm, output_stl_path)
    return output_stl_path
